### ISSUE TITLE
The factorial implementation is suboptimal

### ISSUE THREAD

**Issue by treeowl** [bos/math-functions#21]
The factorial function in this package produces Doubles, and does so by multiplying together Doubles. This is both absurdly inefficient and less precise than it can be. Since Doubles only can handle factorials up to 170!, I don't really see any good reason not to use a carefully-manufactured table with all of them:

https://github.com/downloads/treeowl/factorial-stuff/factorials.hs

This also includes a trivially-produced table of Integer factorials, and a fairly silly table-lookup Int factorial.

**Comment by Shimuuar** [comment]
Fixed in deca9b9775a26bba34a219630b0bf3ed7fb26dcb
