### ISSUE TITLE
unknown symbol `expm1' (windows)

### ISSUE THREAD

**Issue by Jaxan** [bos/math-functions#49]
Hi!

I was installing `random-fu` which depends on your library and got the following error message:

```
[...]
ghc.exe: unable to load package `math-functions-0.2.0.1'
ghc.exe: C:\Users\joshua\Documents\PhD\Code\FSMs\.cabal-sandbox\x86_64-windows-ghc-7.10.3\math-functions-0.2.0.1-9MCqDJNYasuJ7jjxm3Fr23\HSmath-functions-0.2.0.1-9MCqDJNYasu
J7jjxm3Fr23.o: unknown symbol `expm1'
```

Using version 1.7 (which did not have expm1 yet) solved the issue for me.
This might be windows (10) related.

**Comment by Shimuuar** [comment]
I feared it will happen. I'll try to reproduce it. Hopefully it could be passed by adding link flags to cabal. Otherwise I'll have to implement expm1 in haskell.

**Comment by Shimuuar** [comment]
I cannot reproduce the issue on Win10 64bit. What windows are you using?

**Comment by Jaxan** [comment]
I too have Win10 with 64bits. I have a pretty vanilla install (no MinGW or Cygwin, only VS).

**Comment by Shimuuar** [comment]
How did you install haskell? I used stack so difference could be in
installation method.

**Comment by Jaxan** [comment]
I installed the Haskell Platform with ghc 7.10.
I can try to update to a newer release, but that'll take some time (I will have to do it anyways at some point).

**Comment by Jaxan** [comment]
Ok I just installed Haskell Platform 8.0.1, and now it builds!

**Comment by Shimuuar** [comment]
I used stack and GHC-7.10.3 and everything worked fine. I'll try to
reproduce issue with haskell platform.

**Comment by Jaxan** [comment]
If it's not possible to reproduce (for either of us), then maybe it has to do with some Windows update and we can close the issue.
