### ISSUE TITLE
Problem on windows with `_expm1`

### ISSUE THREAD

**Issue by ggreif** [bos/math-functions#51]
I'll just leave this here: cchalmers/plots#22

Strangely `math-functions-0.2.0.2` compiles nicely, but cannot be loaded!?

**Comment by Shimuuar** [comment]
it's because compilation fails during linking. Can you compile simple console program which uses math-functions? Something like:

```
main = print $ expm1 1
```

**Comment by ggreif** [comment]
I cannot reproduce now, because I have `math-functions-0.1.7.0` installed, and cannot upgrade. But looking at
- [`expm1`](https://msdn.microsoft.com/en-us/library/dn353645.aspx)
- [`exp`](https://msdn.microsoft.com/en-us/library/c850xxez.aspx)
the former is only available in _VS2013_ (and up) but the latter is present universally.

Could one make a `CPP` trick to detect it? Or a `cabal` install flag to fall back to `exp(x) - 1` or such?

**Comment by Shimuuar** [comment]
Fallback to `exp x - 1` goes contrary to purpose of expm1 so I guess only way forward is to implement expm1 in haskell

Surely windows is divine punishments for something

**Comment by ggreif** [comment]
@Shimuuar yep, I think reimplementing `expm1` in Haskell when the library does not provide it is the way to go.

**Comment by Shimuuar** [comment]
Fixed in 0.2.1.0 (I hope). It would be nice if you would test it on windows.

## Changes in 0.2.1.0

  * `log1p` and `expm1` are simply reexported from `GHC.Float`. They're methods
     of `Floating` type class.

  * On windows `expm1` is implemented in pure haskell for older GHCs.

**Comment by ggreif** [comment]
@Shimuuar confirmed on windows, thanks!
