### ISSUE TITLE
Feature request: don't use TemplateHaskell

### ISSUE THREAD

**Issue by vmchale** [bos/math-functions#60]
Currently, `TemplateHaskell` is used in various places, e.g. https://github.com/bos/math-functions/blob/master/Numeric/Sum.hs#L101 for `derivingUnbox`. If those instances were written by hand, it would be feasible to cross-compile.

Thanks!

**Comment by Shimuuar** [comment]
AFAIR it's only used to derive Unbox instances. I'm not ready to write _that_ much boilerplate. But if someone will I'll gladly accept patches

**Comment by RyanGlScott** [comment]
I believe #61 implemented this.

**Comment by Shimuuar** [comment]
Indeed. Thanks for pointing it out
