### ISSUE TITLE
Documentation of incompleteBeta is not correct.

### ISSUE THREAD

**Issue by naohaq** [bos/math-functions#62]
https://github.com/bos/math-functions/blob/aa53a8d67e58e1e0bfd623425d55b2a5e62bceb5/Numeric/SpecFunctions/Internal.hs#L585
The integrand should be `t^{a-1}(1-t)^{b-1}` .

**Comment by Shimuuar** [comment]
Thanks! Fix uploaded as part of 0.3.4.0
